app:
  name: pingrb
  mode: normal
  entry_path: /sources

appearance:
  tint_color: "#047857"
  background_color: "#FFFFFF"

tabs:
  - title: sources
    path: /sources
    icon: list.bullet
  - title: devices
    path: /devices
    icon: iphone

ruby_native:
  app_id: app_4ntttyoq
